### ISSUE TITLE
gofast prefixes the $_SERVER['REQUEST_URI'] with the script name

### ISSUE THREAD

**Issue by ijt** [yookoala/gofast#30]
I used this:

        cf := gofast.SimpleConnFactory("unix", pathToPhpFpmSocket)
        var h http.Handler = gofast.NewHandler(
                gofast.NewFileEndpoint(router)(gofast.BasicSession),
                gofast.SimpleClientFactory(cf, 0),
        )

In my script called `index.php` I had

     <?php
     echo $_SERVER['REQUEST_URI']

Expected output:

    /

Actual output:

    /index.php/

**Comment by yookoala** [comment]
Just tested against the php test server (`php -S localhost:8080 ./index.php`), the expected behavior:

* Request: http://localhost:8080/
   `$_SERVER['REQUEST_URI']`: `"/"`
* Request: http://localhost:8080/index.php
   `$_SERVER['REQUEST_URI']`: `"/index.php"`
* Request: http://localhost:8080/index.php/
   `$_SERVER['REQUEST_URI']`: `"/index.php/"`
* Request: http://localhost:8080/abc.php/
   `$_SERVER['REQUEST_URI']`: `"/abc.php/"`
