### ISSUE TITLE
Can you help? What's wrong with the code? The error is at the bottom as commented.

### ISSUE THREAD

**Issue by hiqsociety** [yookoala/gofast#40]
Can you help? What's wrong with the code? The error is at the bottom as commented.

https://play.golang.org/p/IT3YNfP27Lp

**Comment by yookoala** [comment]
The [http.FileSystem](https://golang.org/pkg/net/http/#FileSystem) output should be wrapped by [http.FileServer](https://golang.org/pkg/net/http/#FileServer) before [http.Handle](https://golang.org/pkg/net/http/#Handle). So instead of this:

```go
// handles static assets in the assets folder
http.Handle("/assets/",
	http.StripPrefix("/assets/",
		http.FileSystem(http.Dir("/var/www/html/assets"))))
```

It should be rewritten as such:

```go
// handles static assets in the assets folder
http.Handle("/assets/",
	http.StripPrefix("/assets/",
		http.FileServer(
			http.FileSystem(http.Dir("/var/www/html/assets")))))
```

I got my example wrong. Sorry.
I'm fixing it now.

Thanks for the report
