### ISSUE TITLE
Doesn't work with the original libfcgi

### ISSUE THREAD

**Issue by superchalupa** [yookoala/gofast#65]
The original libfcgi has:

libfcgi/fcgiapp.c, in ProcessBeginRecord():
```
if(requestId == 0 || data->contentLen != sizeof(body)) {
    return FCGX_PROTOCOL_ERROR;
}
```

Which means that it rejects requests with RequestID == 0.

Changing gofast/client.go line 101:
`                for i := uint16(0); i < maxID; i++ {`

to:
`                for i := uint16(1); i < maxID; i++ {`

will resolve this.

Additionally: I'm concerned because it appears that this will run out of ids at 65k and it's not clear what happens then.

**Comment by yookoala** [comment]
Nice catch! Will take a look. Thanks!

**Comment by yookoala** [comment]
> Additionally: I'm concerned because it appears that this will run out of ids at 65k and it's not clear what happens then.

The ID pool is suppose to recover released IDs. If none released, it is going to run out of them and block new ID allocations. We're using uint16 for IDs. The maximum available integer of uint16, which should be 2<sup>16</sup> - 1 = 65535.

According to the [specification](https://fast-cgi.github.io/spec#33-records), the requestID is stored in exactly 2 bytes, which is a 16bit integer. And since we [should not reuse ID before the old request of it has closed](https://fast-cgi.github.io/spec#managing-request-ids), this library is purposely programmed to wait until the old IDs are released.
